spring:
  application:
    name: deadendFairytale

  jackson:
    serialization:
      write-dates-as-timestamps: false   # ??? ? timestamp ?? ?? ISO ??? ??

  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  config:
    import: optional:file:.env[.properties]

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
          ssl:
            trust: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token:
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}