spring:
  application:
    name: deadendFairytale

  jackson:
    serialization:
      write-dates-as-timestamps: false   # ??? ? timestamp ?? ?? ISO ??? ??

  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  config:
    import: optional:file:.env[.properties]

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token:
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}